### PR TITLE
Create zh_cn.json 1.19.2

### PR DESCRIPTION
**Pull request by Yizhouuu**
contributor: yizhouuu

### CODE REVIEW

**Comment by Yizhouuu** [comment]
btw i dont exactly know whats "Antiblock" meaning

**Comment by PlatinPython** [comment]
First of all, thank you for the translation.

To help you with the confusion about the "Antiblock", that block is more or less a copy of the "Antiblock" from Chisel, so you can probably just copy the translation from there.

Now there's one thing I'm wondering, why did you translate most "RGB" with, what DeepL tells me, means "colorful"?
Not that that is in any way wrong, I just want to understand your reasoning behind not just using "RGB".

**Comment by Yizhouuu** [comment]
> To help you with the confusion about the "Antiblock", that block is more or less a copy of the "Antiblock" from Chisel, so you can probably just copy the translation from there.

thanks, im asking the translator of Chisel

> Now there's one thing I'm wondering, why did you translate most "RGB" with, what DeepL tells me, means "colorful"?
Not that that is in any way wrong, I just want to understand your reasoning behind not just using "RGB".

Eastern and Western language systems differ so significantly that it can feel unnatural to insert English words into Eastern sentences, such as "RGB 方块" or "使用 RGB 方块模组来建筑". Therefore, we generally prefer to translate all English words into Chinese. Also, you can't directly transliterate English letters into Chinese like Korean ("아르지비") or Japanese ("アールジービー") do.

So I chose to translate RGB as "多彩", which is also a form of literary adaptation. However, this translation does slightly alter the original meaning. If you prefer to preserve the term "RGB", I'm open to adjusting the translation, modder's original ideas is also a factor i should consider.

**Comment by PlatinPython** [comment]
Thank you for the clear explanation. I see no reason to keep the "RGB" given your explanation. 
One thing I would like to request is, to use a translation that means "Colorable" instead, unless that is already the case.

**Comment by Yizhouuu** [comment]
👌i will think out a better translation recently and commit

**Comment by Yizhouuu** [comment]
I have changed all "多彩" to "调色", which may lose some literal meaning but conveys the usage of the mod "dyeable" more accurately. I have also adapted the translation of 'paint bucket' to match it. Machine translation might not be able to translate it correctly to English, but it looks fine in Chinese now.

**Comment by PlatinPython** [comment]
Perfect, thank you. Unless there is anything you want to change, I would merge it later.

**Comment by Yizhouuu** [comment]
nothing else to change👍

**Pull request merged**
